### ISSUE TITLE
Remove Murpheus as a dependancy?

### ISSUE THREAD

**Issue by v2thegreat** [Social-Media-Public-Analysis/dozent#26]
During testing of the usage of Dozent to download some tweets, I realized that a lot of packages were being installed with the intention of being used for Murpheus. 

AFAIK, there isn't a ton of functionality that comes from Murpheus and we want to ensure that Dozent is as lightweight as possible. 

Because of this, I think it'll be a good idea to remove Murpheus. 

I'll make a relevant branch that can do that without any problems and remove all functionality to simplify Dozent

**Comment by erb13020** [comment]
Considering we want Dozent and Murpheus to be microservices, I think this is the best course of action to take.

**Comment by erb13020** [comment]
Resolved by PR #28
