### ISSUE TITLE
Issues with getting dozent to download data (broken downloader)

### ISSUE THREAD

**Issue by v2thegreat** [Social-Media-Public-Analysis/dozent#8]
Getting an issue with dozent when I was trying to download twitter data. 

Things tried:

  - installing dozent via `setup.py`
  - calling on dozent manually

Both times, got different issues:

Installing dozent via setup.py

![image](https://user-images.githubusercontent.com/22357311/102805268-f631bc80-4388-11eb-9185-3a4e67882507.png)

Calling on dozent manually:

![image](https://user-images.githubusercontent.com/22357311/102805335-12cdf480-4389-11eb-9418-f79f08b0c025.png)

**Comment by erb13020** [comment]
Fixed with PR #12
